Feature/hue
vanttec/vanttec_classic_vision pull request #1
Opened 2020-05-04 03:26 UTC by vSebas

2020-05-04 20:11 UTC, ivanacollg requested changes

2020-05-04 20:11 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   data.Hue(0,105,5);
define todos estos parametros como variables al inicio del programa

2020-05-04 20:11 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  cv::Mat dst_, Hsv2Bgr;
usa la matriz ya definida out_ en lugar de dst_

2020-05-04 20:11 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  for(int hue_ = min_hue; hue_ <= max_hue; hue_ += step){
hue_ es una variable local de la funcion, por lo que no debería de tener guion bajo, eso es solo para variables de la clase.

2020-05-04 20:12 UTC, ivanacollg commented
Modifica brief de files para que  tu seas coautor y fecha de ultima edicion. Y resuelve merge conflicts

2020-05-05 23:53 UTC, vSebas commented
Considero que la modificación del brief debe de hacerse luego de hacer merge a todos los pull request, para evitar poner lo mismo en todos.

2020-05-06 17:41 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   data.Hue(0,105,5);
Done

2020-05-06 17:41 UTC, vSebas commented on src/data_augmentation.cpp
> +  cv::Mat dst_, Hsv2Bgr;
Done

2020-05-06 17:42 UTC, vSebas commented on src/data_augmentation.cpp
> +  for(int hue_ = min_hue; hue_ <= max_hue; hue_ += step){
Done

2020-05-06 17:55 UTC, ivanacollg requested changes
No se te olvide arreglar los merge conflicts. Entiendo que no quieres modificar los headers de todos, pero modificalos en solo en este , para no hacer un pull request solo de eso.

2020-05-06 17:55 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   u_char min_hue=0,max_hue=105,step=5;
no las declares variables en un mismo renglon. Lo que puedes haces es commentar cada bloque de variables por filtro, ejemplo: 
//Hue filter
min_hue
ma_hue
... etc

2020-05-06 17:55 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   data.Hue(min_hue,max_hue,step);
agrega espacio entre comas

2020-05-06 22:17 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   u_char min_hue=0,max_hue=105,step=5;
Done

2020-05-06 22:18 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   data.Hue(min_hue,max_hue,step);
Done

2020-05-19 05:04 UTC, merged