Feature/rename images
vanttec/vanttec_classic_vision pull request #11
Opened 2020-08-08 01:09 UTC by vSebas

2020-08-12 22:02 UTC, ivanacollg requested changes

2020-08-12 22:02 UTC, ivanacollg commented on src/rename_augmented_images.cpp
> +    DataAugmentation data;
Creo que este objeto de data augmentation no se necesita

2020-08-12 22:02 UTC, ivanacollg commented on src/rename_augmented_images.cpp
> +            strcpy(old_name,(class_path+file).c_str());
duda, para que tienes que copiar los strings?

2020-11-08 01:15 UTC, vSebas commented on src/rename_augmented_images.cpp
> +    DataAugmentation data;
Indeed

2020-11-08 01:44 UTC, vSebas commented on src/rename_augmented_images.cpp
> +            strcpy(old_name,(class_path+file).c_str());
Porque la funci[on rename no acepta strings directamente. Son necesarios char arrays.

2020-11-08 01:51 UTC, vSebas commented on src/rename_augmented_images.cpp
> +    DataAugmentation data;
Done

2020-11-08 02:05 UTC, merged