Obtain scaling of three subimages UPPER, MIDDLE, LOWER based on given…
vanttec/vanttec_classic_vision pull request #3
Opened 2020-05-04 03:27 UTC by vSebas

… ratio

2020-05-04 20:35 UTC, ivanacollg requested changes
Arregla los merge conflics y modifica los headers de los files como coautor y fecha modificada

2020-05-04 20:35 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   data.Scaling_ROI(1);
declara los parameros de la funcion como variables al inicio del codigo

2020-05-04 20:35 UTC, ivanacollg commented on src/data_augmentation.cpp
> +    int w_ = std::round(ratio*in_.cols);
renombra variables w_ y h_ sin guin bajo porque son variables locales de la funcion. Nombrarlas con nombre mas descriptivo. Ejemplo: width y height

2020-05-04 20:35 UTC, ivanacollg commented on src/data_augmentation.cpp
> +      if(i == 0){
Cambia estos tres ifs por un int switch

2020-05-04 20:35 UTC, ivanacollg commented on src/data_augmentation.cpp
> +      cv::imwrite("../../imgs/Scale_UPPER_x_"+std::to_string(ratio)+".png",
no le pongas mayusculas a los paths de salida

2020-05-04 20:35 UTC, ivanacollg commented on src/data_augmentation.cpp
> +      cv::Mat croppedImage_ = image_(ROI);
cropped image es una variable local, por lo que no lleva guin bajo. Usa out_ el lugar de cropped image

2020-05-04 20:35 UTC, ivanacollg commented on src/data_augmentation.cpp
> +    cv::Mat image_ = in_.clone();
cambia el nombre de image_ a temp ya que es una matriz temporaria en lo que llegas a out_. Y no lleva gion bajo porque es variable de la funcion, no de la clase

2020-05-06 17:40 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   data.Scaling_ROI(1);
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +    int w_ = std::round(ratio*in_.cols);
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +      if(i == 0){
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +      cv::imwrite("../../imgs/Scale_UPPER_x_"+std::to_string(ratio)+".png",
Done

2020-05-06 17:41 UTC, vSebas commented on src/data_augmentation.cpp
> +      cv::Mat croppedImage_ = image_(ROI);
Done

2020-05-06 17:41 UTC, vSebas commented on src/data_augmentation.cpp
> +    cv::Mat image_ = in_.clone();
Done

2020-05-06 17:58 UTC, ivanacollg commented
Arregla merge conflicts

2020-05-19 04:49 UTC, merged