Added feature/brightness
vanttec/vanttec_classic_vision pull request #4
Opened 2020-05-04 05:38 UTC by vSebas

2020-05-04 21:03 UTC, ivanacollg requested changes
Agrega tu nombre como coautor al header y la fecha que se modifico por ultima vez

2020-05-04 21:03 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   data.Brightness(80);
define el parametro como variable al inicio del programa

2020-05-04 21:03 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  double alpha_ = 1.0;
varibles de funciones no llevan guion bajo: alpha

2020-05-04 21:03 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  int beta_ = brightness;
sin guion bajo beta. No veo la necesidad de declarar otra variable beta, si podemos usar el argumento brightness directamente

2020-05-04 21:03 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  int i,j;
Estas declarando las variables i y j dos veces. Sugiero decrlarar aqui i y c, para no declararlas adentro de los for

2020-05-04 21:03 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  cv::imwrite("../../imgs/Brightness:"+ std::to_string(beta_)+".png", out_);
paths de outputs sin mayusculas

2020-05-04 21:03 UTC, ivanacollg commented on src/data_augmentation.cpp
> +  double alpha_ = 1.0;
Comnenta tambien lo que controla alpha: contraste y agregalo como parametro a la funcion, igual que brightness

2020-05-06 17:40 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   data.Brightness(80);
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +  double alpha_ = 1.0;
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +  int beta_ = brightness;
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +  int i,j;
Done

2020-05-06 17:40 UTC, vSebas commented on src/data_augmentation.cpp
> +  cv::imwrite("../../imgs/Brightness:"+ std::to_string(beta_)+".png", out_);
Done

2020-05-06 18:08 UTC, ivanacollg requested changes

2020-05-06 18:08 UTC, ivanacollg commented on src/data_augmentation.cpp
> +void DataAugmentation::ContrastBrightness(const double alpha, const int beta){
En lugar de llamar los parametros aloha o beta, llamalos dependiendo  lo que controlan. No estoy segura cual es cual, pero uno controla brightness y el otro contraste.

2020-05-06 18:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   int beta=80;
Agrega espacios antes y despues de signo =

2020-05-06 18:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
>     int kernel_size=5;
Yo se que yo hice esto, pero si puedes agregar espacios antes y despues de los signos = en general en todo.

2020-05-06 18:08 UTC, ivanacollg commented on src/data_augmentation.h
> +  // @param alpha[in]: contrast control
Si puedes agregar al comentario el rango acceptable, ejemplo: (0-3)

2020-05-06 18:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +   double alpha=1.0;
Agrega comentario antes de los dos  //ContrastBrightness params

2020-05-06 18:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
>     int kernel_size=5;
Agrega comentario // Bluss Params arriba de int kernel_size

2020-05-06 21:56 UTC, vSebas commented on src/test/data_augmentation_test.cpp
>     int kernel_size=5;
Mejor lo cambio en master

2020-05-06 22:02 UTC, vSebas commented on src/data_augmentation.cpp
> +void DataAugmentation::ContrastBrightness(const double alpha, const int beta){
Done

2020-05-06 22:02 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   int beta=80;
Done

2020-05-06 22:03 UTC, vSebas commented on src/test/data_augmentation_test.cpp
>     int kernel_size=5;
Mejor lo cambio en master

2020-05-06 22:03 UTC, vSebas commented on src/data_augmentation.h
> +  // @param alpha[in]: contrast control
Done

2020-05-06 22:03 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +   double alpha=1.0;
Done

2020-05-19 02:29 UTC, vSebas commented on src/test/data_augmentation_test.cpp
>     int kernel_size=5;
Done

2020-05-19 04:41 UTC, merged