Feature/filter combination
vanttec/vanttec_classic_vision pull request #6
Opened 2020-06-28 20:47 UTC by vSebas

2020-06-28 22:07 UTC, ivanacollg requested changes
Primer review.

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +#include <time.h>
Aqui no debe de haber ningun include aparte de "include/data_augmentation.h"

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +    DataAugmentation data;
Agregar comentarios para descripcion de de cada parametro.

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +    int combination;
Inicializar todos los parametros.  Ejemplo: int kernel_size = 0 ;

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +    data.ReadDirectory("../../imgs/",images);
Agregar parametro string de [ara el path.

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +    data.Save("../../Filtered_imgs/");
Agregar path como parametro string.

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +        contrast = 1.0;
Todos los parametros que no cambian como este, pueden ir afuera del for, polos directamente cuando declaras la variable.

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +#include <time.h>
los .h solo se incluyen en "data_augmentation.h"

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +cv::Mat DataAugmentation::getIN(){
Funcion syntax: GetIn

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +void DataAugmentation::setIN(cv::Mat in){
function name: SetIn

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +std::vector<cv::Mat> DataAugmentation::getOUT(){
Function syntax GetOut

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +void DataAugmentation::setOUT(std::vector<cv::Mat> out){
function syntax SetOut

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
>          //return -1; // unsuccessful
Porque esta comentado este return? Sabes para que sirve?

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +// #include <time.h>
Borrar este commentario si no es necesario

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  cv::Mat getIN();
Function syntax GetIn

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  void setIN(cv::Mat);
Function syntax SetIn

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  std::vector<cv::Mat> getOUT();
Function syntax GetOut

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  void setOUT(std::vector<cv::Mat>);
Function Syntax SetOut

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  // Delete las element from out_
last*

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  // no params
*No params

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
>      data.Read("../../imgs/lena.png");
Agregrar path como parametro sting.

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save("../../Filtered_imgs/");
Agregrar path como parametro sting.

2020-06-28 22:07 UTC, ivanacollg commented on src/data_augmentation.cpp
> +// INCLUDES --------------------------------------------------------------------
Agregar Brief de documento

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
>      double contrast = 1.0;
contraste puede ser int? Y si no cambiar a float para tener variable types unifomes

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    std::vector<std::string> images;
agregar descripcion de vector images

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    srand(time(NULL));
descripcion para esete parametro

2020-06-28 22:07 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
>      cv::Mat in;
Se necesitan las matrices in y out en este codigo?

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  // Get in_
Una descripcion mas descriptiva: Que es in_?

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  // Get out_
Una descripcion mas descriptiva: Que es out_?

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.h
> +  // @param images[in]: jpg saved images
jpg o png? mejor no pongas el formato de las imagenes aqui

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +  in_ = cv::imread(path, 1);
cambiar paramero 1 a  la bandera IMREAD_COLOR para que sea mas facil del leer el codigo

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
>    int i,j;
No declarar dos variabes en una misma linea.

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
>    int column_pixel, row_pixel, color;
no declarar variablas variables en una linea

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
>    int i,j,c;
no declarar varias variables en una fila

2020-06-28 22:07 UTC, ivanacollg commented on src/include/data_augmentation.cpp
> +    cv::imwrite(path+"robosub2020_"+std::to_string(j + 1)+".jpg", out_[j]);
agregar la parte se robosub2020_ al path string parameter

2020-06-30 01:57 UTC, vSebas commented on src/data_augmentation.cpp
> +#include <time.h>
Done

2020-06-30 02:05 UTC, vSebas commented on src/data_augmentation.cpp
> +    int combination;
Done

2020-06-30 02:07 UTC, vSebas commented on src/data_augmentation.cpp
> +    data.ReadDirectory("../../imgs/",images);
Done

2020-06-30 02:10 UTC, vSebas commented on src/data_augmentation.cpp
> +    data.Save("../../Filtered_imgs/");
Done

2020-06-30 02:14 UTC, vSebas commented on src/include/data_augmentation.cpp
> +  in_ = cv::imread(path, 1);
Done

2020-06-30 02:14 UTC, vSebas commented on src/include/data_augmentation.cpp
>    int i,j;
Done

2020-06-30 02:16 UTC, vSebas commented on src/include/data_augmentation.cpp
>    int column_pixel, row_pixel, color;
Done

2020-06-30 02:16 UTC, vSebas commented on src/include/data_augmentation.cpp
>    int i,j,c;
Done

2020-06-30 02:18 UTC, vSebas commented on src/include/data_augmentation.cpp
> +    cv::imwrite(path+"robosub2020_"+std::to_string(j + 1)+".jpg", out_[j]);
Done

2020-06-30 02:36 UTC, vSebas commented on src/data_augmentation.cpp
> +        contrast = 1.0;
Done

2020-06-30 02:37 UTC, vSebas commented on src/include/data_augmentation.cpp
> +#include <time.h>
Done

2020-06-30 02:39 UTC, vSebas commented on src/include/data_augmentation.cpp
> +cv::Mat DataAugmentation::getIN(){
Done

2020-06-30 02:40 UTC, vSebas commented on src/include/data_augmentation.cpp
> +std::vector<cv::Mat> DataAugmentation::getOUT(){
Done

2020-06-30 02:40 UTC, vSebas commented on src/include/data_augmentation.cpp
> +void DataAugmentation::setOUT(std::vector<cv::Mat> out){
Done

2020-06-30 02:41 UTC, vSebas commented on src/include/data_augmentation.cpp
>          //return -1; // unsuccessful
La verdad no, cuando empezamos a trabajar en todo esto eso ya estaba

2020-06-30 02:41 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +// #include <time.h>
Done

2020-06-30 02:42 UTC, vSebas commented on src/include/data_augmentation.h
> +  cv::Mat getIN();
Done

2020-06-30 02:42 UTC, vSebas commented on src/include/data_augmentation.h
> +  void setIN(cv::Mat);
Done

2020-06-30 02:42 UTC, vSebas commented on src/include/data_augmentation.h
> +  std::vector<cv::Mat> getOUT();
Done

2020-06-30 02:42 UTC, vSebas commented on src/include/data_augmentation.h
> +  void setOUT(std::vector<cv::Mat>);
Done

2020-06-30 02:42 UTC, vSebas commented on src/include/data_augmentation.h
> +  // Delete las element from out_
Done

2020-06-30 02:43 UTC, vSebas commented on src/include/data_augmentation.h
> +  // no params
Done

2020-06-30 02:45 UTC, vSebas commented on src/test/data_augmentation_test.cpp
>      data.Read("../../imgs/lena.png");
Done

2020-06-30 02:46 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save("../../Filtered_imgs/");
Done

2020-06-30 02:46 UTC, vSebas commented on src/data_augmentation.cpp
> +// INCLUDES --------------------------------------------------------------------
Done

2020-06-30 02:49 UTC, vSebas commented on src/test/data_augmentation_test.cpp
>      double contrast = 1.0;
Float, done

2020-06-30 02:50 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    std::vector<std::string> images;
Done

2020-06-30 02:50 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    srand(time(NULL));
Deleted, done

2020-06-30 02:50 UTC, vSebas commented on src/test/data_augmentation_test.cpp
>      cv::Mat in;
Deleted, done

2020-06-30 02:53 UTC, vSebas commented on src/include/data_augmentation.h
> +  // Get in_
Done

2020-06-30 02:53 UTC, vSebas commented on src/include/data_augmentation.h
> +  // Get out_
Done

2020-06-30 02:54 UTC, vSebas commented on src/include/data_augmentation.h
> +  // @param images[in]: jpg saved images
Done

2020-07-03 14:05 UTC, merged