Removed directory iteration and added the ShowOut and Save method per…
vanttec/vanttec_classic_vision pull request #9
Opened 2020-07-11 04:43 UTC by vSebas

… filter

2020-07-11 18:05 UTC, ivanacollg commented
Modificar la funcion de save para que ya no ome el numero de la imagen como parametro. Modifica data_augmentation.cpp ejecutable para que agregue el numero de la imagen al string antes de pasarlo como parameyro a save.

2020-07-12 05:08 UTC, ivanacollg requested changes

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Cambiar que cada imagen se guarde con el nombre del filtro correspondiente en lugar de con un numero. Esto evita que las imagenes se sobreescriban en caso de que se corra por accidente este codigo test en lugar de el verdadero ejecutable.

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
cambiar en el nombre el numero de imagen por filtro _hue

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
cambiar en el nombre el numero de imagen por filtro _noise

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
cambiar en el nombre el numero de imagen por filtro _brightness

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
cambiar en el nombre el numero de imagen por filtro _sacling1

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
cambiar en el nombre el numero de imagen por filtro _sacling2

2020-07-12 05:08 UTC, ivanacollg commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
cambiar en el nombre el numero de imagen por filtro _sacling3

2020-07-13 02:32 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Done

2020-07-13 02:32 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Done

2020-07-13 02:32 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Done

2020-07-13 02:32 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Done

2020-07-13 02:32 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Done

2020-07-13 02:32 UTC, vSebas commented on src/test/data_augmentation_test.cpp
> +    data.Save(filtered_images+std::to_string(++i),extension); // Save output image
Done

2020-07-13 03:33 UTC, merged